require("user.options")
require("user.keymaps")
require("user.emmet")
require("user.plugins")
require("user.neotree")
require("user.windowpicker")
require("user.colorscheme")
require("user.cmp")
require("user.ultisnip")
require("user.lsp")
-- require("user.lsp_signature") -- removed it for now because of noice.vim( seems to give better syntax)
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.lualine1")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
-- require("user.alpha")
require("user.whichkey")
require("user.autocommands")
require("user.startify")
require("user.customcompile")
require("user.autotag")
require("user.winbar")
require("user.navic")
require("user.icons")
require("user.functions")
require("user.illuminate")
-- require "user.rooter"
require("user.luasnip")
require("user.noice")
require("user.navbuddy")
require("user.dapui")
-- require("user.colorizer")
-- require("user.barbecue")
-- require("user.wilder")
--[[ require("user.ssr") ]]

